### ISSUE TITLE
Torrent is not being seeded

### ISSUE THREAD

**Issue by qwuzzy** [ManlyMarco/HS2-HF_Patch#10]
Unable to download the file from the magnet :(

**Comment by ManlyMarco** [comment]
Use latest version of qBittorrent and magnet from the latest patch release.

**Comment by qwuzzy** [comment]
I already was, but it won't download metadata unfortunately.

**Comment by ManlyMarco** [comment]
It can take a couple of minutes, especially if you don't have an open port. Could also be a case of traffic being blocked.
