### ISSUE TITLE
Updater-related issues

### ISSUE THREAD

**Issue by dmcjohnny** [ManlyMarco/HS2-HF_Patch#13]
Hi, I have installed and used your HF patch for HoneySelect2 v2.5.
However, in use, I tried to use the updater that came with the launcher, but then during the update process, my network repeatedly appeared connection loss. This resulted in multiple failed updates.
I then checked the mod folder and found that there were many files with the same name, I would like to ask whether these files with the same name can be deleted? And the consequences of deletion?
In addition, I also found that the updater does not seem to save the files from the previous failed work, is it related to the duplicate files?
Finally, thank you for the patch and look forward to your reply.

**Comment by ManlyMarco** [comment]
Hello, just run the updater again and it will clean up any unnecessary files.

**Comment by dmcjohnny** [comment]
Okay, I get it. Thanks.
