### ISSUE TITLE
Floating startup window

### ISSUE THREAD

**Issue by mun3d** [ManlyMarco/HS2-HF_Patch#16]
The startup windows needs window management bars on the top so it can be moved around. It plants itself in the middle of your screen and waits there a LOOOOOONg time waiting to start and can't be minimized off the screen.

**Comment by ManlyMarco** [comment]
Update BepInEx.SplashScreen to v2.2 whenever it is released or wait for the next version of HF Patch. In the meantime you can disable the splash screen in plugin settings.
