### ISSUE TITLE
Feature request  

### ISSUE THREAD

**Issue by mun3d** [ManlyMarco/HS2-HF_Patch#17]
In the game in the characters screen, can you add the floating window for other outfits?

**Comment by ManlyMarco** [comment]
Not sure what exactly you mean.

**Comment by mun3d** [comment]
In the game open up characters, and then clothing. (room screen)  I have so many coordination's I need them in folders by theme. Only the ones in the top folder can show up. If we had the floating window then we could change folders to better keep organized.

**Comment by ManlyMarco** [comment]
Sounds like this is what you want: https://github.com/ManlyMarco/Illusion_BrowserFolders/issues/36
Moving discussion over to that issue
