### ISSUE TITLE
Savegame complete and missing mods

### ISSUE THREAD

**Issue by natsukirei** [ManlyMarco/HS2-HF_Patch#18]
Hey guys

So i downloaded a bunch of mods, did the updates, and i have a heap of missing mods for male and female characters from the ModPack in the Chara folders

Also i cant figure out how to activate the 100% full save game mod.

**Comment by ManlyMarco** [comment]
If you installed the latest HF Patch, run update from launcher. Skip studio modpack if you don't use studio.

You have to check the full save game when installing the patch. It will overwrite current progress. Alternatively press F12 and use cheat tools to unlock things.

**Comment by natsukirei** [comment]
i finally got the mods working, i just did all the downloads ( 323 GB x.x )

But the savegame confuses me, so many rooms are locked, and the VIP section all the scenes are locked and require something

**Comment by ManlyMarco** [comment]
Available rooms depend on the characters and their own stats.

**Comment by natsukirei** [comment]
that makes more sense now, sorry im new to this game and mods, does that apply to the stuff u can do? i noticed under "female-led" theirs only two options but ive installed the female lead mod for extra options

**Comment by ManlyMarco** [comment]
Yes, full save only unlocks the achievements and perks.
