### ISSUE TITLE
HS2_PovX mod is not working in this pack

### ISSUE THREAD

**Issue by yuhyuhyuhD** [ManlyMarco/HS2-HF_Patch#2]
I might just be dumb but i dont think that the HS2_PovX mod is working for this pack when using the controls listed on his page nothing happens 

BTW thank you for putting these mod packs together youre a legend man <3

**Comment by ManlyMarco** [comment]
Go to plugin settings and search for the pov plugin's settings. Maybe the plugin didn't get installed, or the hotkey is set to something else. Try installing the latest version from here https://github.com/FairBear/HS2_PovX/releases/latest

**Comment by ManlyMarco** [comment]
Changed PovX to be installed by default in the latest version of the patch.

**Comment by yuhyuhyuhD** [comment]
ok thank you man!
