### ISSUE TITLE
When playing after a while, the recycle bin is filled to the brim with character save files

### ISSUE THREAD

**Issue by lolersaurus** [ManlyMarco/HS2-HF_Patch#3]
Which plugin could have caused this? And how do I turn it off? I tried disabling the autosave plugin but it did not help. 
Also, I know this is HS2, but the same thing is also happening in AISyoujyo, recycle bin being absolutely filled with character save files.

**Comment by ManlyMarco** [comment]
It's caused by the RemoveToRecycleBin plugin and it's working as intended since in AI/HS2 the character cards themselves get overwritten every time you save the game.

**Comment by lolersaurus** [comment]
I see, if I remove the plugin, will it cause problem? I just have to delete the dll, right?

**Comment by ManlyMarco** [comment]
No, you will just lose the safety of always having old copies of your cards.

**Comment by lolersaurus** [comment]
I think I can live with that, thanks!
