### ISSUE TITLE
Little bug that skips first time in a map.

### ISSUE THREAD

**Issue by applejack-okami** [ManlyMarco/HS2-HF_Patch#4]
I enjoy this patch so much, but this new one has an issue or it could be a Plug-in mistake.
I sure that before entering any map with a girl for the first time, you get a small conversation scene, and after this patch this small interaction wont run so it skips to the sex game.
I need some help with this.

Thank you.

**Comment by ManlyMarco** [comment]
Can you try to narrow it down? Does it still happen if you disable all mods by removing the winhttp.dll file from game directory?

**Comment by Comic19** [comment]
Is there a game body@

**Comment by ManlyMarco** [comment]
Issue can't be reproduced, closing until someone that can reproduce it comes forward and helps fix it.
