### ISSUE TITLE
Achievements page is not working

### ISSUE THREAD

**Issue by blueslippers** [ManlyMarco/HS2-HF_Patch#6]
When applying the patch on the steam DX version the achievements page stop working. You have to reboot the game to exit the achievements page.

**Comment by ManlyMarco** [comment]
It's probably something in userdata/save causing it, you can remove the save folder if you don't mind losing progress and it should be fixed. If you care about the save and/or want to help fix the issue, send me the output_log from game directory after opening the achievement screen. If you can, DM me on discord so it's easier to talk.

**Comment by ManlyMarco** [comment]
A fix for this is distributed through the game launcher > update, next patch will come with it included.
