### ISSUE TITLE
after hf patch applied, network connection seems broken

### ISSUE THREAD

**Issue by cpeng03d** [ManlyMarco/HS2-HF_Patch#7]
Hi I am hoping to get some help on this,
after hf patch is applied to the base game, the network connection seems broken.
when network option at main menu is selected, either ai downloader or hs downloader or uploader cannot connect to server anymore.
they all says server error.
I cannot see other people's character creation.
Did hf patch moved network to somewhere else?
how to access network now?
thank you.

**Comment by ManlyMarco** [comment]
In-game servers will not work with a modded game, a custom server is necessary but currently there are none. You can get and upload cards to db.bepis.moe and the IS discord server instead.
