### ISSUE TITLE
After installing the mod, HoneySelect 2 is in japanese

### ISSUE THREAD

**Issue by CavaleriOmar** [ManlyMarco/HS2-HF_Patch#9]
I installed everything in the game file folder, the launcher of the mod starts without any problems (in which I choose English as the language), but on launch the game is stuck on Japanese

Launcher: Steam + Proton
OS: Arch-based Linux

**Comment by CavaleriOmar** [comment]
Thank you for the library detail. Solved.

In the spirit of collegiality towards other linux users, I would like to specify that in order to solve it, I had to remove the Steam launcher and reinstall Honey Select 2 via Lutris, and then install the patch again via Lutris.

You don't have to add the launcher to Steam, because if you try to boot from there, there are discrete graphical problems.

**Comment by torvic9** [comment]
Sorry for digging this one out, but the game crashes at startup with the 'winhttp' override, shortly after the white Illusion startup screen.
Without 'winhttp' it starts with the obvious downsides.

It has been working quite well until the big Steam client update. I reinstalled both game and mod, and cleaned the wine/proton prefix as well as the actual game folder. Using Proton 7.0 (as this one worked in the past) and Linux 6.4.

The only error message I can find is:

```
wine: Unhandled page fault on write access to 0000759FA04F3A18 at address 0000759FB34C07B2
```

**Comment by ManlyMarco** [comment]
@torvic9  Start the game outside of steam and see if that helps. You have to reinstall HF Patch after every game update. Make sure you aren't running out of RAM.
